// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("bs-react/src/ReasonReact.bs.js");

var component = ReasonReact.statelessComponent(undefined, undefined, "App-ParcelBsReactApp");

function make(name, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* jsElementWrapped */component[/* jsElementWrapped */2],
          /* render */(function (_self) {
              var match = React.useState(0);
              var setCounter = match[1];
              var counter = match[0];
              return React.createElement("div", {
                          onClick: (function (_event) {
                              return setCounter(counter + 1 | 0);
                            })
                        }, "Hello! " + (name + (": " + String(counter))));
            })
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
