// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("bs-react/src/ReactDOMRe.bs.js");
var ReasonReact = require("bs-react/src/ReasonReact.bs.js");
var App$ParcelBsReactApp = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ParcelBsReactApp.make("Parcel", /* array */[])), "root");

/*  Not a pure module */
